Repository cherrypic-proj/cherrypic-server, pull requests merged in 2025-07, with the labels that each got.

#25 feat: DB 설정 및 Flyway 초기 설정
  .gitignore
  cherrypic-api/build.gradle
  cherrypic-api/src/main/resources/application-local.yml
  cherrypic-api/src/test/java/org/cherrypic/CherrypicApiApplicationTests.java
  cherrypic-api/src/test/java/resources/application-test.yml
  cherrypic-domain/build.gradle
Labels: ✨ feature

#23 chore: Spring Security 설정
  cherrypic-api/build.gradle
  cherrypic-api/src/main/java/org/cherrypic/global/config/security/SecurityConfig.java
Labels: ⚙️ chore

#29 feat : 도메인 설계 및 DB 스크립트 작성
  cherrypic-domain/build.gradle
  cherrypic-domain/src/main/java/org/cherrypic/album/entity/Album.java
  cherrypic-domain/src/main/java/org/cherrypic/album/repository/AlbumRepository.java
  cherrypic-domain/src/main/java/org/cherrypic/event/entity/Event.java
  cherrypic-domain/src/main/java/org/cherrypic/event/entity/EventImage.java
  cherrypic-domain/src/main/java/org/cherrypic/event/repository/EventImageRepository.java
  cherrypic-domain/src/main/java/org/cherrypic/event/repository/EventRepository.java
  cherrypic-domain/src/main/java/org/cherrypic/favorites/entity/Favorites.java
  cherrypic-domain/src/main/java/org/cherrypic/favorites/enums/FavoriteStatus.java
  cherrypic-domain/src/main/java/org/cherrypic/favorites/repsoitory/FavoritesRepository.java
  cherrypic-domain/src/main/java/org/cherrypic/image/entity/Image.java
  cherrypic-domain/src/main/java/org/cherrypic/image/repository/ImageRepository.java
  cherrypic-domain/src/main/java/org/cherrypic/member/entity/Member.java
  cherrypic-domain/src/main/java/org/cherrypic/member/entity/OauthInfo.java
  cherrypic-domain/src/main/java/org/cherrypic/member/enums/MemberRole.java
  cherrypic-domain/src/main/java/org/cherrypic/member/enums/MemberStatus.java
  cherrypic-domain/src/main/java/org/cherrypic/member/repository/MemberRepository.java
  cherrypic-domain/src/main/java/org/cherrypic/participant/entity/Participant.java
  cherrypic-domain/src/main/java/org/cherrypic/participant/enums/ParticipantRole.java
  cherrypic-domain/src/main/java/org/cherrypic/participant/repository/ParticipantRepository.java
  cherrypic-domain/src/main/java/org/cherrypic/payment/entity/Payment.java
  cherrypic-domain/src/main/java/org/cherrypic/payment/enums/PaymentStatus.java
  cherrypic-domain/src/main/java/org/cherrypic/payment/repository/PaymentRepository.java
  cherrypic-domain/src/main/java/org/cherrypic/subscription/entity/Subscription.java
  cherrypic-domain/src/main/java/org/cherrypic/subscription/enums/SubscriptionStatus.java
  cherrypic-domain/src/main/java/org/cherrypic/subscription/enums/SubscriptionType.java
  cherrypic-domain/src/main/java/org/cherrypic/subscription/repository/SubscriptionRepository.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
Labels: ✨ feature

#37 test: 테스트 격리
  cherrypic-api/src/test/java/org/cherrypic/DatabaseCleaner.java
  cherrypic-api/src/test/java/org/cherrypic/IntegrationTest.java
Labels: ✅ test

#40 feat: 현재 로그인한 회원 조회 유틸 추가
  cherrypic-api/src/main/java/org/cherrypic/domain/auth/exception/AuthErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/member/exception/MemberErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/member/exception/MemberException.java
  cherrypic-api/src/main/java/org/cherrypic/global/util/MemberUtil.java
Labels: ✨ feature

#48 chore: 인증 실패 시 401 상태 코드 반환 처리
  cherrypic-api/src/main/java/org/cherrypic/global/config/security/SecurityConfig.java
Labels: ⚙️ chore

#51 feat: 로그아웃 기능 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/auth/controller/AuthController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/auth/service/AuthService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/auth/service/AuthServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/auth/util/CookieUtil.java
  cherrypic-api/src/main/java/org/cherrypic/global/config/security/SecurityConfig.java
  cherrypic-api/src/test/java/org/cherrypic/auth/controller/AuthControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/auth/service/AuthServiceTest.java
  cherrypic-api/src/test/resources/application-test.yml
Labels: ✨ feature

#55 feat: 앨범 생성 기능 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/album/controller/AlbumController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/request/AlbumCreateRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/response/AlbumCreateResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/album/entity/Album.java
  cherrypic-domain/src/main/java/org/cherrypic/album/enums/AlbumType.java
  cherrypic-domain/src/main/java/org/cherrypic/member/entity/OauthInfo.java
  cherrypic-domain/src/main/java/org/cherrypic/participant/entity/Participant.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
  cherrypic-domain/src/main/resources/db/migration/V2__alter_member_table_rename_profile_column.sql
  cherrypic-domain/src/main/resources/db/migration/V3__alter_member_table_remove_not_null_from_profile_image_url_column.sql
Labels: ✨ feature

#61 feat: 앨범 유료 플랜 결제 준비 기능 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/request/AlbumCreateRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/response/AlbumCreateResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/controller/PaymentController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/dto/PaymentReadyRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/dto/PaymentReadyResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/exception/PaymentErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/exception/PaymentException.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/service/PaymentService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/service/PaymentServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/controller/PaymentControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/service/PaymentServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/album/entity/Album.java
  cherrypic-domain/src/main/java/org/cherrypic/album/enums/AlbumPlan.java
  cherrypic-domain/src/main/java/org/cherrypic/album/enums/AlbumType.java
  cherrypic-domain/src/main/java/org/cherrypic/payment/entity/Payment.java
  cherrypic-domain/src/main/java/org/cherrypic/subscription/entity/Subscription.java
  cherrypic-domain/src/main/java/org/cherrypic/subscription/enums/SubscriptionType.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
Labels: ✨ feature

#65 feat: 앨범 초대 링크 생성 API 구현
  cherrypic-api/build.gradle
  cherrypic-api/src/main/java/org/cherrypic/domain/album/controller/AlbumController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/response/InvitationLinkCreateResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/exception/AlbumErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/InvitationLinkService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/exception/ParticipantErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/exception/ParticipantException.java
  cherrypic-api/src/test/java/org/cherrypic/RedisCleaner.java
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/controller/EventControllerTest.java
  cherrypic-domain/src/main/java/org/cherrypic/album/entity/InvitationCode.java
  cherrypic-domain/src/main/java/org/cherrypic/album/repository/InvitationCodeRepository.java
  cherrypic-domain/src/main/java/org/cherrypic/participant/repository/ParticipantRepository.java
Labels: ✨ feature

#73 refactor: 도메인 레포지토리 및 QueryDSL 설정 API 모듈로 이동
  cherrypic-api/build.gradle
  cherrypic-api/src/main/java/org/cherrypic/domain/album/repository/AlbumRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/repository/InvitationCodeRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/auth/repository/RefreshTokenRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/auth/service/AuthServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/auth/service/JwtTokenService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/repository/EventImageRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/repository/EventRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/service/EventServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/favorites/FavoritesRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/ImageRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/member/repository/MemberRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/repository/ParticipantRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/repository/PaymentRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/service/PaymentServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/repository/SubscriptionRepository.java
  cherrypic-api/src/main/java/org/cherrypic/global/config/querydsl/QuerydslConfig.java
  cherrypic-api/src/main/java/org/cherrypic/global/util/MemberUtil.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/auth/service/AuthServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/image/service/ImageServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/member/repository/MemberRepositoryTest.java
  cherrypic-api/src/test/java/org/cherrypic/member/service/MemberServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/service/PaymentServiceTest.java
  cherrypic-domain/build.gradle
Labels: ♻️ refactor

#74 feat: 참여 중인 앨범 목록 조회 API 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/album/controller/AlbumController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/response/AlbumListResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/repository/AlbumRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/repository/AlbumRepositoryCustom.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/repository/AlbumRepositoryImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/global/pagination/SliceResponse.java
  cherrypic-api/src/main/java/org/cherrypic/global/pagination/SortDirection.java
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
Labels: ✨ feature
