Repository cherrypic-proj/cherrypic-server, pull requests merged in 2025-09, with the labels that each got.

#188 feat: 앨범 결제 내역 목록 조회 API 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/controller/PaymentController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/dto/response/PaymentListResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/exception/PaymentErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/repository/PaymentRepositoryCustom.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/repository/PaymentRepositoryImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/service/PaymentService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/service/PaymentServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/payment/controller/PaymentControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/service/PaymentServiceTest.java
Labels: ✨ feature

#191 feat: 앨범 구독 정보 조회 API 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/controller/SubscriptionController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/dto/response/SubscriptionInfoResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/service/SubscriptionService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/service/SubscriptionServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/subscription/controller/SubscriptionControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/subscription/service/SubscriptionServiceTest.java
Labels: ✨ feature

#197 test: 테스트 환경을 H2에서 MySQL로 전환 및 Flyway 적용
  .github/workflows/ci.yml
  cherrypic-api/src/test/java/org/cherrypic/DatabaseCleaner.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
  cherrypic-api/src/test/resources/application-test.yml
  cherrypic-domain/src/main/resources/db/migration/V3__create_temp_album_and_temp_album_image_table.sql
  docker-compose-test.yml
Labels: ✅ test

#199 fix: 이미지 추가/삭제와 관련된 앨범 용량 추가/감소 로직 추가
  cherrypic-api/src/main/java/org/cherrypic/domain/image/controller/ImageController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/dto/request/AlbumFileUploadRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/dto/request/UploadFailedFileDeleteRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/dto/response/PresignedUrlsResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/dto/response/UploadFileListResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/ImageRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/ImageRepositoryCustom.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/ImageRepositoryImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/service/ImageService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/service/ImageServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/image/controller/ImageControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/image/service/ImageServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/image/entity/Image.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
Labels: 🐛 bug/error

#203 refactor: 이미지 도메인 DTO명 수정 및 S3util infra 모듈로 이동
  build.gradle
  cherrypic-api/src/main/java/org/cherrypic/domain/image/controller/ImageController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/dto/request/AlbumImageUploadRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/dto/request/ImageUploadRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/dto/response/ImageUploadListResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/event/ImageEventListener.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/service/ImageService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/service/ImageServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/image/controller/ImageControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/image/service/ImageServiceTest.java
  cherrypic-infrastructure/build.gradle
  cherrypic-infrastructure/src/main/java/org/cherrypic/s3/S3Util.java
  cherrypic-infrastructure/src/main/java/org/cherrypic/s3/enums/FileExtension.java
  cherrypic-infrastructure/src/main/java/org/cherrypic/s3/enums/ImageType.java
Labels: ♻️ refactor

#205 feat: 구독 만료된 앨범에 대한 주요 쓰기 요청 제한 로직 적용
  cherrypic-api/src/main/java/org/cherrypic/domain/album/exception/AlbumErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/service/EventServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/service/ImageServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/service/ParticipantServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/service/PaymentServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/service/SubscriptionServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/controller/EventControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/image/controller/ImageControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/image/service/ImageServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/participant/controller/ParticipantControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/participant/service/ParticipantServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/controller/PaymentControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/service/PaymentServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/subscription/controller/SubscriptionControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/subscription/service/SubscriptionServiceTest.java
Labels: ✨ feature

#212 feat: 결제 취소 및 환불 처리 기능 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/controller/PaymentController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/repository/PaymentRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/service/PaymentService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/service/PaymentServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/service/SubscriptionServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/controller/PaymentControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/service/PaymentServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/subscription/controller/SubscriptionControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/subscription/service/SubscriptionServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/payment/entity/Payment.java
  cherrypic-domain/src/main/java/org/cherrypic/payment/exception/PaymentDomainErrorCode.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
Labels: ✨ feature

#217 refactor: 불필요한 양방향 연관관계 제거 및 단방향 설계로의 구조 개선
  cherrypic-api/src/main/java/org/cherrypic/domain/album/repository/AlbumRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/repository/AlbumRepositoryImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/repository/EventRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/service/EventServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/favorites/exception/FavoritesErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/favorites/repository/FavoritesRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/favorites/service/FavoritesServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/EventImageRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/ImageRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/service/ImageServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/notification/repository/NotificationRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/repository/ParticipantRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/service/ParticipantServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/repository/PaymentRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/service/PaymentServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/service/SubscriptionServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/participant/service/ParticipantServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/subscription/service/SubscriptionServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/album/entity/Album.java
  cherrypic-domain/src/main/java/org/cherrypic/participant/entity/Participant.java
Labels: ♻️ refactor

#219 feat: 앨범 목록 조회 API에 구독 상태 필터링 기능 추가
  cherrypic-api/src/main/java/org/cherrypic/domain/album/controller/AlbumController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/response/AlbumListResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/repository/AlbumRepositoryCustom.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/repository/AlbumRepositoryImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
Labels: ✨ feature

#223 fix: 유료 앨범 삭제 시 연관 구독·결제 엔티티까지 함께 제거되도록 수정
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/repository/PaymentRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/repository/SubscriptionRepository.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
Labels: 🐛 bug/error
