Repository cherrypic-proj/cherrypic-server, pull requests merged in 2025-08, with the labels that each got.

#76 feat: 이벤트 삭제 기능 구현
  build.gradle
  cherrypic-api/src/main/java/org/cherrypic/domain/event/controller/EventController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/repository/EventImageRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/service/EventService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/service/EventServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/event/controller/EventControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/event/entity/Event.java
  cherrypic-domain/src/main/java/org/cherrypic/event/entity/EventImage.java
  cherrypic-domain/src/main/java/org/cherrypic/image/entity/Image.java
Labels: ✨ feature

#81 feat: 앨범 수정 기능 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/album/controller/AlbumController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/request/AlbumUpdateRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/response/AlbumUpdateResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/exception/AlbumErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/album/entity/Album.java
Labels: ✨ feature

#84 refactor: 인증, 회원 도메인 테스트 코드 리팩토링
  cherrypic-api/src/test/java/org/cherrypic/auth/controller/AuthControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/auth/service/AuthServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/member/controller/MemberControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/member/repository/MemberRepositoryTest.java
  cherrypic-api/src/test/java/org/cherrypic/member/service/MemberServiceTest.java
Labels: ♻️ refactor

#87 feat: 참가자 초대 API 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/album/controller/AlbumController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/response/AlbumJoinResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/exception/AlbumErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/resources/static/.well-known/apple-app-site-association
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
Labels: ✨ feature

#103 refactor: 이벤트 이미지 관리 방식 변경
  cherrypic-api/src/main/java/org/cherrypic/domain/event/repository/EventImageRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/repository/EventRepositoryImpl.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/event/entity/Event.java
  cherrypic-domain/src/main/java/org/cherrypic/event/entity/EventImage.java
  cherrypic-domain/src/main/java/org/cherrypic/image/entity/Image.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
Labels: ♻️ refactor

#88 feat: 앨범 삭제 API 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/album/controller/AlbumController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/exception/AlbumErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/repository/ParticipantRepository.java
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
Labels: ✨ feature

#106 feat: 이미지 목록 조회 API 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/album/controller/AlbumController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/controller/EventController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/exception/EventErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/service/EventServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/controller/ImageController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/dto/response/ImageListResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/ImageRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/ImageRepositoryCustom.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/ImageRepositoryImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/service/ImageService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/service/ImageServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/controller/EventControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/image/controller/ImageControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/image/service/ImageServiceTest.java
Labels: ✨ feature

#107 feat: FCM 푸시 알림 기능 구현
  build.gradle
  cherrypic-api/build.gradle
  cherrypic-api/src/main/java/org/cherrypic/domain/album/event/AlbumDeleteEvent.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/member/controller/MemberController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/member/dto/request/FcmTokenSaveRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/member/service/MemberService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/member/service/MemberServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/notification/event/AlbumDeleteEventListener.java
  cherrypic-api/src/main/java/org/cherrypic/domain/notification/repository/NotificationRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/notification/service/FcmService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/notification/service/FcmTokenService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/notification/service/NotificationService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/notification/service/NotificationServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/repository/ParticipantRepository.java
  cherrypic-api/src/main/java/org/cherrypic/global/config/async/AsyncConfig.java
  cherrypic-api/src/main/resources/application.yml
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/member/controller/MemberControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/member/service/MemberServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/notification/service/NotificationServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/album/entity/Album.java
  cherrypic-domain/src/main/java/org/cherrypic/notification/entity/Notification.java
  cherrypic-domain/src/main/java/org/cherrypic/notification/enums/NotificationType.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
  cherrypic-infrastructure/build.gradle
  cherrypic-infrastructure/src/main/java/org/cherrypic/fcm/FcmConfig.java
Labels: ✨ feature

#115 feat: 앨범 나가기 기능 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/album/exception/AlbumErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/controller/ParticipantController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/service/ParticipantService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/service/ParticipantServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/participant/controller/ParticipantControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/participant/service/ParticipantServiceTest.java
Labels: ✨ feature

#118 refactor: EventImage 관리 방식 리팩토링
  build.gradle
  cherrypic-api/build.gradle
  cherrypic-api/src/main/java/org/cherrypic/domain/event/exception/EventErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/repository/EventRepositoryImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/service/EventServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/controller/ImageController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/dto/response/AlbumImageListResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/dto/response/EventImageListResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/exception/ImageErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/EventImageRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/ImageRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/ImageRepositoryCustom.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/repository/ImageRepositoryImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/service/ImageService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/service/ImageServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/global/config/retry/RetryConfig.java
  cherrypic-api/src/test/java/org/cherrypic/event/controller/EventControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/image/controller/ImageControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/image/service/ImageServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/event/entity/EventImage.java
  cherrypic-domain/src/main/java/org/cherrypic/image/entity/Image.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
Labels: ♻️ refactor

#119 feat: 참가자 강퇴 기능 구현
  build.gradle
  cherrypic-api/src/main/java/org/cherrypic/domain/album/exception/AlbumErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/notification/repository/NotificationRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/controller/ParticipantController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/service/ParticipantService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/service/ParticipantServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/participant/controller/ParticipantControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/participant/service/ParticipantServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/notification/entity/Notification.java
Labels: ✨ feature

#121 feat: 이벤트 이미지 제거 API 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/event/controller/EventController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/dto/request/EventImageRemoveRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/exception/EventErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/service/EventService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/event/service/EventServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/event/controller/EventControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
Labels: ✨ feature

#127 fix: 이벤트 이미지 누락된 테스트 추가
  cherrypic-api/src/test/java/org/cherrypic/event/controller/EventControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/album/entity/InvitationCode.java
Labels: 🐛 bug/error

#140 feat: 회원 프로필 수정 API 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/member/controller/MemberController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/member/dto/request/MemberProfileUpdateRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/member/dto/response/MemberProfileUpdateResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/member/service/MemberService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/member/service/MemberServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/member/controller/MemberControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/member/service/MemberServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/member/entity/Member.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
Labels: ✨ feature

#158 feat: 구독 해지 API 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/controller/SubscriptionController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/exception/SubscriptionErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/repository/SubscriptionRepository.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/service/SubscriptionService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/service/SubscriptionServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/subscription/controller/SubscriptionControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/subscription/service/SubscriptionServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/subscription/entity/Subscription.java
  cherrypic-domain/src/main/java/org/cherrypic/subscription/enums/SubscriptionStatus.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
Labels: ✨ feature

#162 feat: 결제 목적 구분을 위한 결제 준비 API 구조 개편
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/dto/request/PaymentReadyRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/dto/response/PaymentReadyResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/exception/PaymentErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/service/PaymentServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/controller/PaymentControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/service/PaymentServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/payment/entity/Payment.java
  cherrypic-domain/src/main/java/org/cherrypic/payment/enums/PaymentPurpose.java
  cherrypic-domain/src/main/java/org/cherrypic/payment/enums/PaymentStatus.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
Labels: ✨ feature

#163 fix: 누락된 ImagesDeleteEvent Listener 추가
  cherrypic-api/src/main/java/org/cherrypic/domain/image/event/ImageEventListener.java
Labels: 🐛 bug/error

#174 feat: 참가자 권한 변경 기능 구현
  cherrypic-api/src/main/java/org/cherrypic/domain/album/exception/AlbumErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/controller/ParticipantController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/dto/request/ParticipantRoleUpdateRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/exception/ParticipantErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/service/ParticipantService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/service/ParticipantServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/participant/controller/ParticipantControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/participant/service/ParticipantServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/participant/entity/Participant.java
  cherrypic-domain/src/main/java/org/cherrypic/participant/enums/ParticipantRole.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
Labels: ✨ feature

#177 refactor: 앨범 플랜, 구독 플랜 등 혼용된 용어를 앨범 유형으로 통일
  cherrypic-api/src/main/java/org/cherrypic/domain/album/controller/AlbumController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/request/AlbumCreateRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/response/AlbumCreateResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/response/AlbumInfoResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/response/AlbumListResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/dto/response/AlbumUpdateResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/exception/AlbumErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/repository/AlbumRepositoryCustom.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/repository/AlbumRepositoryImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumService.java
  cherrypic-api/src/main/java/org/cherrypic/domain/album/service/AlbumServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/service/ImageServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/participant/service/ParticipantServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/controller/PaymentController.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/dto/request/PaymentReadyRequest.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/dto/response/PaymentReadyResponse.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/exception/PaymentErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/payment/service/PaymentServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/exception/SubscriptionErrorCode.java
  cherrypic-api/src/main/java/org/cherrypic/domain/subscription/service/SubscriptionServiceImpl.java
  cherrypic-api/src/test/java/org/cherrypic/album/controller/AlbumControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/album/service/AlbumServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/favorites/service/FavoritesServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/image/service/ImageServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/notification/service/NotificationServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/participant/service/ParticipantServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/controller/PaymentControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/payment/service/PaymentServiceTest.java
  cherrypic-api/src/test/java/org/cherrypic/subscription/controller/SubscriptionControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/subscription/service/SubscriptionServiceTest.java
  cherrypic-domain/src/main/java/org/cherrypic/album/entity/Album.java
  cherrypic-domain/src/main/java/org/cherrypic/album/enums/AlbumType.java
  cherrypic-domain/src/main/resources/db/migration/V1__init.sql
  cherrypic-domain/src/test/java/org/cherrypic/album/entity/AlbumTest.java
Labels: ♻️ refactor

#183 refactor: 중복된 에러 코드 통일
  cherrypic-api/src/main/java/org/cherrypic/domain/event/service/EventServiceImpl.java
  cherrypic-api/src/main/java/org/cherrypic/domain/image/exception/ImageErrorCode.java
  cherrypic-api/src/test/java/org/cherrypic/event/controller/EventControllerTest.java
  cherrypic-api/src/test/java/org/cherrypic/event/service/EventServiceTest.java
Labels: ♻️ refactor
